name: PHP CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      #- name: Install dependencies
      #  run: composer install --prefer-dist --no-progress --no-suggest
      #- name: Run tests
      #  run: ./vendor/bin/phpunit
