name: Deploy to Main

on:
  workflow_run:
    workflows: ["PHP CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login registry.polyweb.cz --username "$DOCKER_USERNAME" --password-stdin

      - name: Build and Deploy
        run: |
          #docker build -t my-custom-image:latest .
          #rancher up --file docker-compose.github.yml --pull --force-upgrade --confirm-upgrade -d --stack $RANCHER_STACK_NAME app
        env:
          RANCHER_ENVIRONMENT: ${{ secrets.RANCHER_ENVIRONMENT }}
          MICROSERVICE_IMAGE: ${{ github.repository }}/${{ github.ref_name }}
          RANCHER_STACK_NAME: "newds"
          WEB_PROJECT_ROOT: "newds"
