name: Deploy

on:
  workflow_run:
    workflows: ["Test", "Build"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u ${{ secrets.COMPOSER_USERNAME }} -p ${{ secrets.COMPOSER_PASSWORD }} registry.polyweb.cz

      - name: Deploy using Rancher
        run: echo "Deploying to Rancher, under construction..."
