name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Composer Validate
        run: composer validate --strict
